#!/bin/bash
#
# First parse arguments

myname=`basename $0`
lnk=`readlink $0`
if [ ! -z "$lnk" ]; then
    cd `dirname $lnk`
    mydir=`pwd -P`
else
    cd `dirname $0`
    mydir=`pwd -P`
fi
export AUTOWRFDIR=`pwd -P`

doconfig=false
namelistonly=false
envvaroverride=false
docompile=false
doclean=false
cleaninput=false
doprepinpt=false
docheckonly=false
dometonly=false
dofinishonly=false
dorun=false
runargs=""
while [ $# -gt 0 ]; do
    case $1 in
    -h|--help)
        echo ""
        echo "$myname: utility to automate the compilation and running of WRF-Chem"
        echo "  Modes of operation: "
        echo ""
        echo "    ./$myname config : will require user input to generate"
        echo "        the necessary configuration files (so don't run this as"
        echo "        part of a batch job). It will also set a global namelist"
        echo "        that will ensure WRF, WPS, and NEI are all set to the same"
        echo "        domain."
        echo ""
        echo "    ./$myname config override : will include the necessary environmental"
        echo "        variables to run WRF-Chem (EM_CORE=1, WRF_CHEM=1, etc) regardless"
        echo "        of how those variables are set in your shell. It will NOT modify"
        echo "        these variables in your shell except when this program is running."
        echo ""
        echo "    ./$myname config namelist : will only reconfigure the"
        echo "        namelist. Useful if you just need to change the domain or"
        echo "        time period."
        echo ""
        echo ""
        echo "    ./$myname compile : will execute the compilation of all"
        echo "        the components of WRF-Chem and it's input preparation,"
        echo "        including WRF-Chem, WPS, convert_emiss, emiss_v0x.F,"
        echo "        megan_bio_emiss, and mozbc. It will skip compiling if"
        echo "        it finds an existing .exe file."
        echo ""
        echo ""
        echo "    ./$myname clean : will remove all compiled files for a clean"
        echo "        compile."
        echo ""
        echo "    ./$myname clean input : will clean up the input files instead."
        echo "        It does not clean the code."
        echo ""
        echo ""
        echo "    ./$myname prepinpt : will prepare meteorology, NEI emissions,"
        echo "        MEGAN emissions, and MOZBC initial and boundary conditions."
        echo ""
        echo "    ./$myname prepinpt check : will just check that everything required"
        echo "        for preparing the input data is ready to go. Add met-only as an"
        echo "        additional argument to only check what is necessary for preparing"
        echo "        meteorology."
        echo ""
        echo "    ./$myname prepinput met-only : will only prepare met data."
        echo ""
        echo "    ./$myname prepinput finish : will only prepare inputs that are missing."
        echo "        Note that this is pretty simple minded with respect to met data, and"
        echo "        will simply assume that WPS succeeded if ANY met_em files are present"
        echo "        in WRFV3/run."
        echo ""
        echo ""
        echo "    ./$myname run : will run WRF-Chem. This will first check"
        echo "        that the WRF namelist.input file matches what was configured"
        echo "        by ./$myname config. If running WRF-Chem in parallel, must pass"
        echo "        the number of tasks to start (x) as --ntasks=x. If running in"
        echo "        serial, must pass the flag --nompi instead"
        echo ""
        echo ""
        echo "  Exit codes for the compile and prepinpt steps will indicate which step"
        echo "  failed using the numeric value as a binary flag. For compile:"
        echo "      1st bit = WRF"
        echo "      2nd bit = WPS"
        echo "      3rd bit = convert_emiss"
        echo "      4th bit = emiss_v0x"
        echo "      5th bit = megan_bio_emiss"
        echo "      6th bit = mozbc"
        echo "  So an exit code of 1 means only WRF failed to compile, while 56 (= 000111)"
        echo "  means emiss_v0x, megan_bio_emiss, and mozbc all failed to compile."
        echo "  The codes are the same for prepinpt, except that the first bit will never"
        echo "  be set."
        echo ""
        echo "  If your cluster has the concept of 'login' vs. 'compute' nodes, i.e. nodes"
        echo "  expected to be used only for light tasks (login) and those for heavy computing"
        echo "  (compute) then 'config', 'clean', and 'prepinpt check' can be safely run on"
        echo "  login-type nodes, but all other modes (including regular prepinpt) should be"
        echo "  run on compute-type nodes. ('compile' is a possible exception, if you normally"
        echo "  do compilation on a login-type node, this should be fine.)"
        echo ""
        echo "  Note that this utility is only set up to handle one domain currently."
        echo ""
        exit 0
        ;;
    config)
        doconfig=true
        ;;
    namelist)
        namelistonly=true
        ;;
    override)
        envvaroverride=true
        ;;
    compile)
        docompile=true
        ;;
    clean)
        doclean=true
        ;;
    input)
        cleaninput=true
        ;;
    prepinpt)
        doprepinpt=true
        ;;
    check)
        docheckonly=true
        ;;
    met-only)
        dometonly=true
        ;;
    finish)
        dofinishonly=true
        ;;
    run)
        dorun=true
        ;;
    --ntasks=*)
        runargs="$runargs $1"
        ;;
    --nompi)
        runargs="$runargs $1"
        ;;
    *)
        echo "$1 is not a recognized option"
        exit 1
        ;;
    esac
    shift
done

# Check that directory structure is intact
cd ..
missingdir=""
if [ ! -d WRFV3 ]; then missingdir="$missingdir WRFV3"; fi
if [ ! -d WPS ]; then missingdir="$missingdir WPS"; fi
if [ ! -d NEI ]; then missingdir="$missingdir NEI"; fi
if [ ! -d MEGAN ]; then missingdir="$missingdir MEGAN"; fi
if [ ! -d MOZBC ]; then missingdir="$missingdir MOZBC"; fi

if [ ! -z "$missingdir" ]; then
    echo "The directory(ies) $missingdir are not present as child directories."
    exit 1
fi


cd $mydir
if $doconfig; then
    configopts=""
    if $namelistonly; then
        configopts="$configopts --namelist-only"
    fi
    if $envvaroverride; then
        configopts="$configopts --override"
    fi
    ./configure $configopts # set env vars and all namelist options.
    configexit=$?

    if [ $configexit -eq 0 ]; then
        if ! $namelistonly; then
            echo ""
            echo "*****************************************************************************"
            echo "Configuration files generated. Run $myname with 'compile' to begin compilation"
            echo "*****************************************************************************"
            echo ""
        fi
    fi
 
    exit $configexit
fi
if $doclean; then
    if $cleaninput; then
        $mydir/cleanall --input
    else
        $mydir/cleanall
    fi
    exit $?
fi
if $docompile; then
    $mydir/compileall
    compexit=$?
    if [ $compexit -ne 0 ]; then
        echo "***********************************************"
        echo "One or more compilations failed (exit status $compexit)"  
        echo "***********************************************"
    fi
    exit $compexit
fi
if $doprepinpt; then
    prepargs=""
    if $docheckonly; then
        prepargs="$prepargs --check-only"
    fi
    if $dometonly; then
        prepargs="$prepargs --met-only"
    fi
    if $dofinishonly; then
        prepargs="$prepargs --finish-only"
    fi
    
    $mydir/prepinpt $prepargs
    exit $?
fi
if $dorun; then
    $mydir/runwrf $runargs
    exit $?
fi

echo "No action specified. See help for usage of $myname."
exit 0

