#!/usr/bin/env python
import os
import sys
from autowrfchem_main import entry_point

no_virt_env = '--no-virt-env' in sys.argv
if no_virt_env:
    sys.argv.remove('--no-virt-env')
else:
    # Am I under a virtual environment? If so, activate it first, then continue
    virt_env_file = os.path.join('..', 'bin', 'activate_this.py')
    if os.path.isfile(virt_env_file):
        print('Found virtual environment, activating {}\n'.format(os.path.abspath(virt_env_file)))
        execfile(virt_env_file, dict(__file__=virt_env_file))

entry_point()