#!/bin/bash

mydir=`dirname $0`
cd $mydir
mydir=`pwd -P`

if [ "$1" == "--check-only" ]; then
    checkonly=true
else
    checkonly=false
fi

# Do a quick check of the most important namelist options
# before starting the prep
PREPINPUT/precheck
chkexit=$?
if [ $chkexit -ne 0 ]; then
    exit $chkexit
fi

if $checkonly; then
    exit 0
fi

# The exit status needs to be 0 if everything works,
# otherwise have bits representing which one failed
# start as 011111 and remove 1's as things succeed
# = 2+4+8+16+32 = 62
exitstat=62

PREPINPUT/prepwps
wpsexit=$?
if [ $wpsexit -eq 0 ]; then
    exitstat=$((exitstat-2))
fi

PREPINPUT/prepnei_intermediate
neiexit=$?
if [ $neiexit -eq 0 ]; then
    exitstat=$((exitstat-4))
fi

PREPINPUT/prepnei_convert
conv.gexit=$?
if [ $conv.gexit -eq 0 ]; then
    exitstat=$((exitstat-8))
fi

PREPINPUT/prepmegan
meganexit=$?
if [ $meganexit -eq 0 ]; then
    exitstat=$((exitstat-16))
fi

PREPINPUT/prepmozbc
mozbcexit=$?
if [ $mozbcexit -eq 0 ]; then
    exitstat=$((exitstat-32))
fi


exit $exitstat
