#!/bin/bash
#
# This will be responsible for running all of the 
# input data prep (WPS, NEI, MEGAN, MOZBC)

mydir=$(dirname $0) # always find this directory, which should be PREPINPUT
cd $mydir
mydir=`pwd -P`
# This must contain definitions of the variables
# metType and metDir. metType must match the ungrib
# Vtable name
. "$mydir/../wrfbuild.cfg"
# This ensures all necessary env. vars. are set
. "$mydir/../envvar_wrfchem.cfg"

#############
#### WPS ####
#############

cd "$mydir/../../WPS"

# Ensure that the WPS namelist is linked to the one in the CONFIG folder
if [ -e namelist.wps ]; then
    # Back up only if not a link already
    lnk=`readlink namelist.wps`
    if [ ! -z $lnk ]; then
        mv namelist.wps namelist.wps.autowrf-backup
    fi
fi
ln -s "$mydir/../CONFIG/namelist.wps"

# First make sure that the GEOGRID table is the ARW_CHEM table
# and that the ungrib Vtable matches the requested meteorology
#
# Backup the GEOGRID.TBL link first. Need to see if it is a link
cd geogrid
if [ -f GEOGRID.TBL ]; then
    lnk=$(readlink GEOGRID.TBL)
    if [ -z $lnk ]; then
        cp GEOGRID.TBL GEOGRID.TBL.BACKUP
    else
        ln -s $lnk GEOGRID.TBL.BACKUP
    fi
fi
# Now link the the ARW_CHEM file
echo "Linking GEOGRID.TBL.ARW_CHEM as GEOGRID.TBL."
ln -sf GEOGRID.TBL.ARW_CHEM GEOGRID.TBL
cd ..

# Now handle the ungrib Vtable link
if [ -f Vtable ]; then
    lnk=$(readlink Vtable)
    if [ -z $lnk ]; then
        cp Vtable Vtable.BACKUP
    else
        ln -s $lnk Vtable.BACKUP
    fi
fi

ln -sf ungrib/Variable_Tables/Vtable.${metType} Vtable


# Begin by running geogrid
./geogrid.exe >& "$mydir/../PREPLOGS/geogrid.log"
ggexit=$?
if [ $ggexit != 0 ]; then
    echo "GEOGRID.exe failed with exit code $ggexit"
    exit 1
fi

# Then ungrib. Need to link the met data first
./link_grib.csh $metDir/$metType
lnkexit=$?
if [ $lnkexit != 0 ]; then
    echo "LINK_GRIB.CSH failed with exit code $lnkexit"
    exit 1
fi
./ungrib.exe >& "$mydir/../PREPLOGS/ungrib.log"
ugexit=$?
if [ $ugexit != 0 ]; then
    echo "UNGRIB.EXE failed with exit code $ugexit"
    exit 1
fi

# Finally metgrid
rm -f met_em*
./metgrid.exe >& "$mydir/../PREPLOGS/metgrid.log"
mgexit=$?
if [ $mgexit != 0 ]; then
    echo "METGRID.EXE failed with exit code $mgexit"
    exit 1
fi

# Now go over to the run directory and link this meteorology
cd ../WRFV3/run
rm -f met_em*
p="../../WPS/met_em*"
for f in $p; do
    ln -s $f
done
